export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";

export const REPLIED_QUERY_REQUEST = "REPLIED_QUERY_REQUEST";
export const REPLIED_QUERY_SUCCESS = "REPLIED_QUERY_SUCCESS";
export const REPLIED_QUERY_FAIL = "REPLIED_QUERY_FAIL";

export const PENDING_QUERY_REQUEST = "PENDING_QUERY_REQUEST";
export const PENDING_QUERY_SUCCESS = "PENDING_QUERY_SUCCESS";
export const PENDING_QUERY_FAIL = "PENDING_QUERY_FAIL";

export const TRANSFERRED_QUERY_REQUEST = "TRANSFERRED_QUERY_REQUEST";
export const TRANSFERRED_SUCCESS = "TRANSFERRED_QUERY_SUCCESS";
export const TRANSFERRED_FAIL = "TRANSFERRED_QUERY_FAIL";

export const SEARCH_QUERY_REQUEST = "SEARCH_QUERY_REQUEST";
export const SEARCH_QUERY_SUCCESS = "SEARCH_QUERY_SUCCESS";
export const SEARCH_QUERY_FAIL = "SEARCH_QUERY_FAIL";

export const SEARCH_QUERY_BY_ID_REQUEST = "SEARCH_QUERY_BY_ID_REQUEST";
export const SEARCH_QUERY_BY_ID_SUCCESS = "SEARCH_QUERY_BY_ID_SUCCESS";
export const SEARCH_QUERY_BY_ID_FAIL = "SEARCH_QUERY_BY_ID_FAIL";

export const SENIOR_JUNIOR_COMPARISON_AIRMAN_PERSMAST_REQUEST = "SENIOR_JUNIOR_COMPARISON_AIRMAN_PERSMAST_REQUEST";
export const SENIOR_JUNIOR_COMPARISON_AIRMAN_PERSMAST_SUCCESS = "SENIOR_JUNIOR_COMPARISON_AIRMAN_PERSMAST_SUCCESS";
export const SENIOR_JUNIOR_COMPARISON_AIRMAN_PERSMAST_FAIL = "SENIOR_JUNIOR_COMPARISON_AIRMAN_PERSMAST_FAIL"; 
export const SENIOR_JUNIOR_COMPARISON_AIRMAN_PERSMAST_RESET = "SENIOR_JUNIOR_COMPARISON_AIRMAN_PERSMAST_RESET";

export const SENIOR_JUNIOR_COMPARISON_AIRMAN_RANKHISTORY_REQUEST = "SENIOR_JUNIOR_COMPARISON_AIRMAN_RANKHISTORY_REQUEST";
export const SENIOR_JUNIOR_COMPARISON_AIRMAN_RANKHISTORY_SUCCESS = "SENIOR_JUNIOR_COMPARISON_AIRMAN_RANKHISTORY_SUCCESS";
export const SENIOR_JUNIOR_COMPARISON_AIRMAN_RANKHISTORY_FAIL = "SENIOR_JUNIOR_COMPARISON_AIRMAN_RANKHISTORY_FAIL";
export const SENIOR_JUNIOR_COMPARISON_AIRMAN_RANKHISTORY_RESET = "SENIOR_JUNIOR_COMPARISON_AIRMAN_RANKHISTORY_RESET";

export const SENIOR_JUNIOR_COMPARISON_AIRMAN_BASICPAY_REASON_REQUEST = "SENIOR_JUNIOR_COMPARISON_AIRMAN_BASICPAY_REASON_REQUEST";
export const SENIOR_JUNIOR_COMPARISON_AIRMAN_BASICPAY_REASON_SUCCESS = "SENIOR_JUNIOR_COMPARISON_AIRMAN_BASICPAY_REASON_SUCCESS";
export const SENIOR_JUNIOR_COMPARISON_AIRMAN_BASICPAY_REASON_FAIL = "SENIOR_JUNIOR_COMPARISON_AIRMAN_BASICPAY_REASON_FAIL";
export const SENIOR_JUNIOR_COMPARISON_AIRMAN_BASICPAY_REASON_RESET = "SENIOR_JUNIOR_COMPARISON_AIRMAN_BASICPAY_REASON_RESET";

export const SENIOR_JUNIOR_COMPARISON_OFFICER_PERSMAST_REQUEST = "SENIOR_JUNIOR_COMPARISON_OFFICER_PERSMAST_REQUEST";
export const SENIOR_JUNIOR_COMPARISON_OFFICER_PERSMAST_SUCCESS = "SENIOR_JUNIOR_COMPARISON_OFFICER_PERSMAST_SUCCESS";
export const SENIOR_JUNIOR_COMPARISON_OFFICER_PERSMAST_FAIL = "SENIOR_JUNIOR_COMPARISON_OFFICER_PERSMAST_FAIL";

export const SENIOR_JUNIOR_COMPARISON_OFFICER_RANK_HISTORY_REQUEST = "SENIOR_JUNIOR_COMPARISON_OFFICER_RANK_HISTORY_REQUEST";
export const SENIOR_JUNIOR_COMPARISON_OFFICER_RANK_HISTORY_SUCCESS = "SENIOR_JUNIOR_COMPARISON_OFFICER_RANK_HISTORY_SUCCESS";
export const SENIOR_JUNIOR_COMPARISON_OFFICER_RANK_HISTORY_FAIL = "SENIOR_JUNIOR_COMPARISON_OFFICER_RANK_HISTORY_FAIL";

export const SENIOR_JUNIOR_COMPARISON_OFFICER_BASIC_PAY_REASON_REQUEST = "SENIOR_JUNIOR_COMPARISON_OFFICER_BASIC_PAY_REASON_REQUEST";
export const SENIOR_JUNIOR_COMPARISON_OFFICER_BASIC_PAY_REASON_SUCCESS = "SENIOR_JUNIOR_COMPARISON_OFFICER_BASIC_PAY_REASON_SUCCESS";
export const SENIOR_JUNIOR_COMPARISON_OFFICER_BASIC_PAY_REASON_FAIL = "SENIOR_JUNIOR_COMPARISON_OFFICER_BASIC_PAY_REASON_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const APP_NAME = 'CRM Dashboard';
