export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";

export const FETCH_PERSONAL_DATA_REQUEST = "FETCH_PERSONAL_DATA_REQUEST";
export const FETCH_PERSONAL_DATA_SUCCESS = "FETCH_PERSONAL_DATA_SUCCESS";
export const FETCH_PERSONAL_DATA_FAIL = "FETCH_PERSONAL_DATA_FAIL";

export const RANK_HISTORY_REQUEST = "RANK_HISTORY_REQUEST";
export const RANK_HISTORY_SUCCESS = "RANK_HISTORY_SUCCESS";
export const RANK_HISTORY_FAIL = "RANK_HISTORY_FAIL";

export const TRADE_HISTORY_REQUEST = "TRADE_HISTORY_REQUEST";
export const TRADE_HISTORY_SUCCESS = "TRADE_HISTORY_SUCCESS";
export const TRADE_HISTORY_FAIL = "TRADE_HISTORY_FAIL";

export const POSTING_HISTORY_REQUEST = "POSTING_HISTORY_REQUEST";
export const POSTING_HISTORY_SUCCESS = "POSTING_HISTORY_SUCCESS";
export const POSTING_HISTORY_FAIL = "POSTING_HISTORY_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const APP_NAME = 'CRM Dashboard';
