export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";

export const REPLIED_QUERY_REQUEST = "REPLIED_QUERY_REQUEST";
export const REPLIED_QUERY_SUCCESS = "REPLIED_QUERY_SUCCESS";
export const REPLIED_QUERY_FAIL = "REPLIED_QUERY_FAIL";

export const SEARCH_QUERY_REQUEST = "SEARCH_QUERY_REQUEST";
export const SEARCH_QUERY_SUCCESS = "SEARCH_QUERY_SUCCESS";
export const SEARCH_QUERY_FAIL = "SEARCH_QUERY_FAIL";

export const SEARCH_QUERY_BY_ID_REQUEST = "SEARCH_QUERY_BY_ID_REQUEST";
export const SEARCH_QUERY_BY_ID_SUCCESS = "SEARCH_QUERY_BY_ID_SUCCESS";
export const SEARCH_QUERY_BY_ID_FAIL = "SEARCH_QUERY_BY_ID_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const APP_NAME = 'CRM Dashboard';
