
export const SEARCH_QUERY_REQUEST = "SEARCH_QUERY_REQUEST";
export const SEARCH_QUERY_SUCCESS = "SEARCH_QUERY_SUCCESS";
export const SEARCH_QUERY_FAIL = "SEARCH_QUERY_FAIL";

export const SEARCH_QUERY_ID_REQUEST = "SEARCH_QUERY_ID_REQUEST";
export const SEARCH_QUERY_ID_SUCCESS = "SEARCH_QUERY_ID_SUCCESS";
export const SEARCH_QUERY_ID_FAIL = "SEARCH_QUERY_ID_FAIL";

export const CLEAR_QUERY_RESULTS = "CLEAR_QUERY_RESULTS";
