
export const SEARCH_QUERY_REQUEST = "SEARCH_QUERY_REQUEST";
export const SEARCH_QUERY_SUCCESS = "SEARCH_QUERY_SUCCESS";
export const SEARCH_QUERY_FAIL = "SEARCH_QUERY_FAIL";

export const SEARCH_QUERY_ID_REQUEST = "SEARCH_QUERY_ID_REQUEST";
export const SEARCH_QUERY_ID_SUCCESS = "SEARCH_QUERY_ID_SUCCESS";
export const SEARCH_QUERY_ID_FAIL = "SEARCH_QUERY_ID_FAIL";

export const CLEAR_QUERY_RESULTS = "CLEAR_QUERY_RESULTS";

export const FAQ_REQUEST = "FAQ_REQUEST";
export const FAQ_SUCCESS = "FAQ_SUCCESS";
export const FAQ_FAIL = "FAQ_FAIL";

export const CLEAR_FAQ_RESULTS = "CLEAR_FAQ_RESULTS";

export const FRQ_QRY_REQUEST = "FRQ_QRY_REQUEST";
export const FRQ_QRY_SUCCESS = "FRQ_QRY_SUCCESS";
export const FRQ_QRY_FAIL = "FRQ_QRY_FAIL";

export const CLEAR_FRQ_QRY_RESULTS = "CLEAR_FRQ_QRY_RESULTS";

